FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# For dev environment
RUN npm install

# Bundle source code
COPY . .

# Start the server
EXPOSE 4000
CMD [ "node", "index.js" ]